version: "3"

networks: 
  yougo:

services:
  hugo:
    build: .
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    ports:
    - 1313:1313
    networks: 
      - yougo
  nginx:
    build: "./nginx"
    ports:
      - "80:80"
    depends_on:
     - "hugo"
    networks: 
      - yougo