version: "3"

networks: 
  hnet:

services:
  hugo:
    # image: alpine
    # command: tail -f /dev/null
    build: .
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    ports:
      #- "1313:1313"
      - 80:80
    # volumes: 
    # - ./site:/site
    networks: 
      - hnet
  # nginx:
  #   build: "./nginx"
  #   ports:
  #     - "80:80"
  #   volumes: 
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  #   depends_on:
  #    - "hugo"
  #   networks: 
  #     - hnet
